name: Arav Narula
description: Blogging about stuffs
meta_description: "Sliding Into The World"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://aravnarula.com/kasper'
google_analytics: ''
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://aravnarula.com/kasper'
author:         'Arav'
